name: flutter_platform_widgets_example
description: Demonstrates how to use the flutter_platform_widgets plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets:
    path: ../
  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
